### ISSUE TITLE
Precomputed Sigs

### ISSUE THREAD

**Issue by connorbybee** [YosefLab/FastProjectR#32]
Error when supplying precomputed sigs from data frame and text file

![image](https://user-images.githubusercontent.com/6521207/34018080-43655488-e0dd-11e7-8047-e4c15cb89a56.png)

**Comment by connorbybee** [comment]
Error when supplying recomputed sigs with text file. When a text file is supplied with N samples separated by tabs on the first line and error is thrown when subsequent lines contain N + 2 tabbed spaces due to signature name and type.

![image](https://user-images.githubusercontent.com/6521207/34018196-b0ff7de8-e0dd-11e7-8b47-c292968dcfdd.png)

**Comment by deto** [comment]
Fixed this at some point - closing.
